import java.util.Properties
import org.jetbrains.compose.desktop.application.dsl.TargetFormat

plugins {
    alias(libs.plugins.kotlinMultiplatform)
    alias(libs.plugins.androidApplication)
    alias(libs.plugins.composeMultiplatform)
    alias(libs.plugins.composeCompiler)
    alias(libs.plugins.kotlinSerialization)
}

// The google-services plugin materializes Firebase config from
// google-services.json (FCM). That file is a credential and is gitignored, so a
// public checkout won't have it — apply the plugin only when it's present. FCM
// then stays inert at runtime (RemotePush falls back to UnifiedPush) rather than
// failing the build. firebase-messaging is still linked (see androidMain) so the
// service compiles regardless.
if (file("google-services.json").exists()) {
    apply(plugin = libs.plugins.googleServices.get().pluginId)
}

// --- Single release version source ---------------------------------------------
// gradle.properties#appVersion / #appVersionCode is the only edit point for a
// release version. Everything below DERIVES from it — Android
// versionName/versionCode, desktop packageVersion, and the runtime AppVersion
// constant (generated Version.kt, see generateVersionKt) — so the four release
// identities can no longer drift apart in-repo. The Release workflow closes the
// remaining gap by asserting the git tag equals v<appVersion> before publishing.
val appVersion: String = providers.gradleProperty("appVersion").get().also {
    require(Regex("""\d+\.\d+\.\d+""").matches(it)) {
        "gradle.properties appVersion must be MAJOR.MINOR.PATCH, got \"$it\""
    }
}
val appVersionCode: Int = providers.gradleProperty("appVersionCode").get().toInt().also {
    require(it > 0) { "gradle.properties appVersionCode must be a positive int" }
}

kotlin {
    androidTarget {
        compilations.all {
            kotlinOptions { jvmTarget = "17" }
        }
    }
    jvm("desktop")

    sourceSets {
        val commonMain by getting {
            dependencies {
                implementation(compose.runtime)
                implementation(compose.foundation)
                implementation(compose.material3)
                implementation(compose.ui)
                implementation(libs.ktor.client.core)
                implementation(libs.ktor.client.content.negotiation)
                implementation(libs.ktor.serialization.json)
                implementation(libs.kotlinx.coroutines.core)
                implementation(libs.kotlinx.serialization.json)
            }
        }
        val commonTest by getting {
            dependencies {
                implementation(kotlin("test"))
            }
        }
        val androidMain by getting {
            dependencies {
                implementation(libs.androidx.activity.compose)
                implementation(libs.ktor.client.okhttp)
                // UnifiedPush: self-hosted push transport (no Google dependency).
                implementation(libs.unifiedpush.connector)
                // FCM: the optional second transport. Linked so HeroFirebaseService
                // compiles; inert at runtime unless google-services.json is present
                // (then RemotePush prefers FCM, else falls back to UnifiedPush).
                implementation(libs.firebase.messaging)
            }
        }
        val desktopMain by getting {
            dependencies {
                implementation(compose.desktop.currentOs)
                implementation(libs.ktor.client.okhttp)
            }
        }
    }
}

// The runtime version constant is GENERATED from the single source above, not
// hand-maintained: v0.5.8 shipped with tag/AppVersion agreement only because a
// human remembered to sync them. Generating the constant makes "binary self-
// reports the tagged version" a build property instead of a review item. The
// file lands in build/generated (never the tree), and inputs.property makes the
// task re-run exactly when appVersion changes.
val generateVersionKt = tasks.register("generateVersionKt") {
    val version = appVersion
    val outDir = layout.buildDirectory.dir("generated/version/commonMain/kotlin")
    inputs.property("appVersion", version)
    outputs.dir(outDir)
    doLast {
        val file = outDir.get().file("io/hero/app/Version.kt").asFile
        file.parentFile.mkdirs()
        file.writeText(
            """
            |// GENERATED by generateVersionKt from gradle.properties#appVersion — do not edit.
            |package io.hero.app
            |
            |// AppVersion is compared against the latest GitHub release tag (see Update.kt).
            |const val AppVersion = "$version"
            |""".trimMargin(),
        )
    }
}
kotlin.sourceSets.getByName("commonMain").kotlin.srcDir(generateVersionKt)

// --- Android release signing --------------------------------------------------
// Signing secrets never live in the repo. Locally, put them in a gitignored
// keystore.properties at the project root (storeFile defaults to
// composeApp/keystore.jks); in CI, release.yml materializes the keystore +
// passwords from GitHub secrets into env. A RELEASE build MUST be signed with the
// real release keystore: a debug-signed release has a different certificate that
// Android refuses to upgrade over a real install, so it is never publishable.
// When no keystore is configured the release build FAILS CLOSED (see the
// taskGraph guard after the android block). The debug fallback is offered only
// for a local build explicitly opted into with -PallowDebugSigningForRelease —
// a flag CI never passes, so a missing/misconfigured secret can't silently ship
// a debug-signed APK.
val keystoreProps = Properties().apply {
    val f = rootProject.file("keystore.properties")
    if (f.exists()) f.inputStream().use { load(it) }
}
fun releaseSecret(propKey: String, envKey: String): String? =
    keystoreProps.getProperty(propKey) ?: System.getenv(envKey)
val releaseStoreFile = file(releaseSecret("storeFile", "KEYSTORE_FILE") ?: "keystore.jks")
val hasReleaseKeystore = releaseStoreFile.exists()
val allowDebugSigningForRelease = hasProperty("allowDebugSigningForRelease")

android {
    namespace = "io.hero.app"
    compileSdk = 34
    defaultConfig {
        applicationId = "io.hero.app"
        minSdk = 24
        targetSdk = 34
        // Derived from gradle.properties (the single version source) — edit there.
        versionCode = appVersionCode
        versionName = appVersion
    }
    signingConfigs {
        create("release") {
            if (hasReleaseKeystore) {
                storeFile = releaseStoreFile
                storePassword = releaseSecret("storePassword", "KEYSTORE_PASSWORD")
                keyAlias = releaseSecret("keyAlias", "KEY_ALIAS")
                keyPassword = releaseSecret("keyPassword", "KEY_PASSWORD")
            }
        }
    }
    buildTypes {
        getByName("release") {
            isMinifyEnabled = false
            // With a real keystore, sign for real. Without one, keep configuration
            // valid (so assembleDebug and unit tests still evaluate on an
            // unconfigured checkout) by pointing at the debug config — but the
            // taskGraph guard below turns an *actual* release assembly into a hard
            // failure unless -PallowDebugSigningForRelease was explicitly given.
            signingConfig = if (hasReleaseKeystore) {
                signingConfigs.getByName("release")
            } else {
                if (allowDebugSigningForRelease) {
                    logger.warn("allowDebugSigningForRelease is set — signing the RELEASE build with the DEBUG key; this artifact is NOT publishable")
                }
                signingConfigs.getByName("debug")
            }
        }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
}

// Fail closed: a release APK must never be debug-signed. Configuration above
// stays valid on an unconfigured checkout (so assembleDebug and unit tests run),
// but scheduling an actual release-packaging task without a real keystore aborts
// the build here. A contributor who deliberately wants a local debug-signed
// release opts in with -PallowDebugSigningForRelease; CI never passes that flag,
// so a release job with a missing/misconfigured keystore fails instead of
// publishing an unupgradable debug-signed APK.
if (!hasReleaseKeystore && !allowDebugSigningForRelease) {
    gradle.taskGraph.whenReady {
        val releaseTask = gradle.taskGraph.allTasks.firstOrNull { t ->
            t.project == project && (t.name == "assembleRelease" || t.name == "packageRelease")
        }
        if (releaseTask != null) {
            throw GradleException(
                "Refusing to build ${releaseTask.path}: no release keystore is configured, so the APK " +
                    "would be signed with the debug key and could never upgrade a real release install. " +
                    "Configure keystore.properties or the KEYSTORE_* env (see .github/workflows/release.yml), " +
                    "or pass -PallowDebugSigningForRelease to build a local debug-signed APK on purpose.",
            )
        }
    }
}

compose.desktop {
    application {
        mainClass = "io.hero.app.MainKt"
        // OkHttp pulls in optional TLS providers / Android classes the desktop JVM
        // lacks; without these -dontwarn rules the release ProGuard pass fails.
        buildTypes.release.proguard {
            configurationFiles.from(project.file("proguard-desktop.pro"))
        }
        nativeDistributions {
            // No Dmg: macOS DMG versions require MAJOR > 0 (validated at Gradle
            // configuration time), which a 0.x appVersion can never satisfy. The
            // format was speculative anyway — CI ships uber jars only, no DMG has
            // ever been built or published — and inventing a second "1.x" version
            // just for it would reintroduce exactly the identity drift this single
            // source removes. Re-adding TargetFormat.Dmg fails the build loudly
            // until the app reaches 1.x (or dmgPackageVersion gets an explicitly
            // decided mapping).
            targetFormats(TargetFormat.Msi, TargetFormat.Deb)
            packageName = "HERO"
            // Derived from gradle.properties (the single version source): names the
            // uber jar (HERO-<os>-<arch>-<version>-release.jar) and is the native
            // package identity. It was a fossilized "1.0.0" before — harmless for
            // the jar-only workflow, but an upgrade-ordering lie the moment native
            // packages ship.
            packageVersion = appVersion
        }
    }
}

// --- Release-artifact smoke (the gate v0.5.7/v0.5.8 lacked) --------------------
// desktopTest runs on the UNSHRUNK Gradle classpath, and
// packageReleaseUberJarForCurrentOS only proves ProGuard + packaging exited 0 —
// v0.5.8's three public jars passed both while their ServiceLoader metadata
// pointed at an engine class ProGuard had stripped, so every install crashed on
// the first Api(...) construction. releaseArtifactSmoke closes that gap against
// the FINAL artifact:
//   1. compileReleaseArtifactSmoke builds a tiny runner (src/releaseSmoke/java)
//      with the uber jar as its ONLY compile classpath — so the shipped jar must
//      still expose the app's API surface;
//   2. releaseArtifactSmoke executes it as a real `java -cp
//      <final-jar>:<smoke-classes>` process (never the Gradle runtime
//      classpath): construct the app's Api, complete one real HTTP request over
//      loopback through it, assert the selected engine is OkHttp and the jar's
//      baked-in AppVersion equals the version source, then close the client.
// Runs locally with ./gradlew :composeApp:releaseArtifactSmoke and in each
// desktop release job on all three OSes.
// A LIVE file collection (re-scanned when consumed) so configuration and
// dependency resolution never fail before the package task has produced the
// jar; the doFirst asserts pin it to exactly one version-matching file at
// execution time.
val releaseUberJars = fileTree(layout.buildDirectory.dir("compose/jars")) {
    include("*-$appVersion-release.jar")
}

fun requireSingleReleaseJar(): Any {
    val jars = releaseUberJars.files
    require(jars.size == 1) {
        "expected exactly one *-$appVersion-release.jar under build/compose/jars " +
            "(run :composeApp:packageReleaseUberJarForCurrentOS), found ${jars.map { it.name }}"
    }
    return jars.single()
}

val compileReleaseArtifactSmoke = tasks.register<JavaCompile>("compileReleaseArtifactSmoke") {
    description = "Compiles the release smoke runner against the final desktop uber jar (its only classpath)."
    dependsOn("packageReleaseUberJarForCurrentOS")
    source(layout.projectDirectory.dir("src/releaseSmoke/java"))
    classpath = releaseUberJars
    destinationDirectory.set(layout.buildDirectory.dir("releaseSmoke/classes"))
    options.release.set(17)
    doFirst { logger.lifecycle("smoke compile classpath (the artifact under test): ${requireSingleReleaseJar()}") }
}

tasks.register<JavaExec>("releaseArtifactSmoke") {
    group = "verification"
    description = "Runs the artifact-level smoke on the final desktop uber jar's real classpath."
    classpath = releaseUberJars + files(compileReleaseArtifactSmoke.flatMap { it.destinationDirectory })
    mainClass.set("io.hero.app.smoke.SmokeRunner")
    args(appVersion)
    doFirst { requireSingleReleaseJar() }
}
